# -*- coding: utf-8 -*-
"""BookShop.ipynb
 Automatically generated by Colab.
 Original file is located at
    https://colab.research.google.com/drive/12wMGGqY7cJKby15IC93SZ_xBNLx-rm-_
"""

def max_pages(n, x, prices, pages):
    dp = [0] * (x + 1)  # dp[j] = Máximo número de páginas con presupuesto j

    for i in range(n):
        price, page = prices[i], pages[i]
        for j in range(x, price - 1, -1):  # Recorremos en orden inverso
            dp[j] = max(dp[j], dp[j - price] + page)

    return dp[x]

# Leer entrada
n, x = map(int, input().split())
prices = list(map(int, input().split()))
pages = list(map(int, input().split()))

# Calcular resultado
print(max_pages(n, x, prices, pages))