# -*- coding: utf-8 -*-
"""5054251017_Soal3.ipynb
 Automatically generated by Colab.
 Original file is located at
    https://colab.research.google.com/drive/1b8P1d7aDxXrPrr2t4X9xS4aXzNpLEh9J
"""

from collections import deque

def count_rooms(n, m, grid):
    visited = [[False] * m for _ in range(n)]
    directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]

    def bfs(start_row, start_col):
        queue = deque([(start_row, start_col)])
        visited[start_row][start_col] = True

        while queue:
            r, c = queue.popleft()
            for dr, dc in directions:
                nr, nc = r + dr, c + dc
                if 0 <= nr < n and 0 <= nc < m and not visited[nr][nc] and grid[nr][nc] == '.':
                    visited[nr][nc] = True
                    queue.append((nr, nc))

    room_count = 0
    for i in range(n):
        for j in range(m):
            if grid[i][j] == '.' and not visited[i][j]:
                room_count += 1
                bfs(i, j)

    return room_count

n, m = map(int, input().split())
grid = [list(input().strip()) for _ in range(n)]
print(count_rooms(n, m, grid))
