import java.io.OutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.InputMismatchException;
import java.io.IOException;
import java.util.TreeSet;
import java.io.InputStream;

/**
 * Code generated by CHelperX2
 */
public class entry_9372654 {
    public static void main(String[] args) {
        InputStream inputStream = System.in;
        OutputStream outputStream = System.out;
        FasterInputReader in = new FasterInputReader(inputStream);
        PrintWriter out = new PrintWriter(outputStream);
        ConcertTickets2 solver = new ConcertTickets2();
        solver.solve(1, in, out);
        out.close();
    }

    static class ConcertTickets2 {
        public void solve(int testNumber, FasterInputReader in, PrintWriter out) {
            int numTickets = in.nextInt();
            int numCustomers = in.nextInt();
            int[] tickets = new int[numTickets];
            int[] maxPay = new int[numCustomers];
            for (int i = 0; i < numTickets; i++) {
                tickets[i] = in.nextInt();
            }
            for (int j = 0; j < numCustomers; j++) {
                maxPay[j] = in.nextInt();
            }
            TreeSet<ConcertTickets2.Pair> ticketPrices = new TreeSet<>();
            for (int i = 0; i < numTickets; i++) {
                ticketPrices.add(new ConcertTickets2.Pair(tickets[i], i));
            }
            for (int j = 0; j < numCustomers; j++) {
                ConcertTickets2.Pair entry = ticketPrices.lower(new ConcertTickets2.Pair(maxPay[j] + 1, -1));
                if (entry == null) {
                    out.println(-1);
                } else {
                    out.println(entry.price);
                    ticketPrices.remove(entry);
                }
            }
        }

        static class Pair implements Comparable<ConcertTickets2.Pair> {
            int price;
            int index;

            public Pair(int price, int index) {
                this.price = price;
                this.index = index;
            }

            public int compareTo(ConcertTickets2.Pair o) {
                int res = Integer.compare(price, o.price);
                if (res == 0) {
                    return Integer.compare(index, o.index);
                }
                return res;
            }

        }

    }

    static class FasterInputReader {
        private InputStream stream;
        private byte[] buf = new byte[1024];
        private int curChar;
        private int numChars;
        private FasterInputReader.SpaceCharFilter filter;

        public FasterInputReader(InputStream stream) {
            this.stream = stream;
        }

        public int get() {
            if (numChars == -1) {
                throw new InputMismatchException();
            }
            if (curChar >= numChars) {
                curChar = 0;
                try {
                    numChars = stream.read(buf);
                } catch (IOException e) {
                    throw new InputMismatchException();
                }
                if (numChars <= 0) {
                    return -1;
                }
            }
            return buf[curChar++];
        }

        public int nextInt() {
            int c = get();
            while (isSpaceChar(c)) {
                c = get();
            }
            int sgn = 1;
            if (c == '-') {
                sgn = -1;
                c = get();
            }
            int res = 0;
            do {
                if (c < '0' || c > '9') {
                    throw new InputMismatchException();
                }
                res *= 10;
                res += c - '0';
                c = get();
            } while (!isSpaceChar(c));
            return res * sgn;
        }

        public boolean isSpaceChar(int c) {
            if (filter != null) {
                return filter.isSpaceChar(c);
            }
            return isWhitespace(c);
        }

        public static boolean isWhitespace(int c) {
            return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
        }

        public interface SpaceCharFilter {
            public boolean isSpaceChar(int ch);

        }

    }
}
